version: '1.0'
services:
  devcode-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3030:3030"
    volumes:
      - ./:/app
    environment:
      - PORT=3030
      - NODE_ENV=development
      - MYSQL_HOST=mysql
    env_file:
      - ./.env
  

    
